#!/usr/bin/env perl
#
# Copyright (c) 2013 Cisco Systems, Inc.  All rights reserved.
#
# $COPYRIGHT$
# 
# Additional copyrights may follow
# 
# $HEADER$
#

#
# Generated constants
#

package FortranMPI::Constants;

use strict;

#============================================================================
# MPI constants
# (each MPI implementation will need to assign their own values, but
# this lists them all)

our @constants;

@constants = qw/
MPI_VERSION
MPI_SUBVERSION
MPI_ANY_SOURCE
MPI_ANY_TAG
MPI_PROC_NULL
MPI_ROOT
MPI_UNDEFINED
MPI_CART
MPI_GRAPH
MPI_DIST_GRAPH
MPI_KEYVAL_INVALID
MPI_SOURCE
MPI_TAG
MPI_ERROR
MPI_BSEND_OVERHEAD
MPI_ORDER_C
MPI_ORDER_FORTRAN

MPI_TAG_UB
MPI_HOST
MPI_IO
MPI_WTIME_IS_GLOBAL
MPI_APPNUM
MPI_LASTUSEDCODE
MPI_UNIVERSE_SIZE

MPI_DISTRIBUTE_BLOCK
MPI_DISTRIBUTE_CYCLIC
MPI_DISTRIBUTE_NONE
MPI_DISTRIBUTE_DFLT_DARG
MPI_TYPECLASS_INTEGER
MPI_TYPECLASS_REAL
MPI_TYPECLASS_COMPLEX
MPI_COMBINER_NAMED
MPI_COMBINER_DUP
MPI_COMBINER_CONTIGUOUS
MPI_COMBINER_VECTOR
MPI_COMBINER_HVECTOR_INTEGER
MPI_COMBINER_HVECTOR
MPI_COMBINER_INDEXED
MPI_COMBINER_HINDEXED_INTEGER
MPI_COMBINER_HINDEXED
MPI_COMBINER_INDEXED_BLOCK
MPI_COMBINER_STRUCT_INTEGER
MPI_COMBINER_STRUCT
MPI_COMBINER_SUBARRAY
MPI_COMBINER_DARRAY
MPI_COMBINER_F90_REAL
MPI_COMBINER_F90_COMPLEX
MPI_COMBINER_F90_INTEGER
MPI_COMBINER_RESIZED
MPI_COMBINER_HINDEXED_BLOCK

MPI_MODE_NOCHECK
MPI_MODE_NOPRECEDE
MPI_MODE_NOPUT
MPI_MODE_NOSTORE
MPI_MODE_NOSUCCEED
MPI_LOCK_EXCLUSIVE
MPI_LOCK_SHARED
MPI_WIN_BASE
MPI_WIN_SIZE
MPI_WIN_DISP_UNIT

MPI_THREAD_SINGLE
MPI_THREAD_FUNNELED
MPI_THREAD_SERIALIZED
MPI_THREAD_MULTIPLE

MPI_SUCCESS
MPI_ERR_BUFFER
MPI_ERR_COUNT
MPI_ERR_TYPE
MPI_ERR_TAG
MPI_ERR_COMM
MPI_ERR_RANK
MPI_ERR_REQUEST
MPI_ERR_ROOT
MPI_ERR_GROUP
MPI_ERR_OP
MPI_ERR_TOPOLOGY
MPI_ERR_DIMS
MPI_ERR_ARG
MPI_ERR_UNKNOWN
MPI_ERR_TRUNCATE
MPI_ERR_OTHER
MPI_ERR_INTERN
MPI_ERR_IN_STATUS
MPI_ERR_PENDING
MPI_ERR_ACCESS
MPI_ERR_AMODE
MPI_ERR_ASSERT
MPI_ERR_BAD_FILE
MPI_ERR_BASE
MPI_ERR_CONVERSION
MPI_ERR_DISP
MPI_ERR_DUP_DATAREP
MPI_ERR_FILE_EXISTS
MPI_ERR_FILE_IN_USE
MPI_ERR_FILE
MPI_ERR_INFO_KEY
MPI_ERR_INFO_NOKEY
MPI_ERR_INFO_VALUE
MPI_ERR_INFO
MPI_ERR_IO
MPI_ERR_KEYVAL
MPI_ERR_LOCKTYPE
MPI_ERR_NAME
MPI_ERR_NO_MEM
MPI_ERR_NOT_SAME
MPI_ERR_NO_SPACE
MPI_ERR_NO_SUCH_FILE
MPI_ERR_PORT
MPI_ERR_QUOTA
MPI_ERR_READ_ONLY
MPI_ERR_RMA_ATTACH
MPI_ERR_RMA_CONFLICT
MPI_ERR_RMA_FLAVOR
MPI_ERR_RMA_RANGE
MPI_ERR_RMA_SHARED
MPI_ERR_RMA_SYNC
MPI_ERR_SERVICE
MPI_ERR_SIZE
MPI_ERR_SPAWN
MPI_ERR_UNSUPPORTED_DATAREP
MPI_ERR_UNSUPPORTED_OPERATION
MPI_ERR_WIN
MPI_T_ERR_MEMORY
MPI_T_ERR_NOT_INITIALIZED
MPI_T_ERR_CANNOT_INIT
MPI_T_ERR_INVALID_INDEX
MPI_T_ERR_INVALID_ITEM
MPI_T_ERR_INVALID_HANDLE
MPI_T_ERR_OUT_OF_HANDLES
MPI_T_ERR_OUT_OF_SESSIONS
MPI_T_ERR_INVALID_SESSION
MPI_T_ERR_CVAR_SET_NOT_NOW
MPI_T_ERR_CVAR_SET_NEVER
MPI_T_ERR_PVAR_NO_STARTSTOP
MPI_T_ERR_PVAR_NO_WRITE
MPI_T_ERR_PVAR_NO_ATOMIC
MPI_T_ERR_INVALID
MPI_ERR_LASTCODE

MPI_IDENT
MPI_CONGRUENT
MPI_SIMILAR
MPI_UNEQUAL

MPI_COMM_TYPE_SHARED

MPI_SEEK_SET
MPI_SEEK_CUR
MPI_SEEK_END
MPI_MODE_CREATE
MPI_MODE_RDONLY
MPI_MODE_WRONLY
MPI_MODE_RDWR
MPI_MODE_DELETE_ON_CLOSE
MPI_MODE_UNIQUE_OPEN
MPI_MODE_EXCL
MPI_MODE_APPEND
MPI_MODE_SEQUENTIAL
MPI_DISPLACEMENT_CURRENT

OMPI_COMM_TYPE_CLUSTER
OMPI_COMM_TYPE_NODE
OMPI_COMM_TYPE_HOST
OMPI_COMM_TYPE_BOARD
OMPI_COMM_TYPE_NUMA
OMPI_COMM_TYPE_SOCKET
OMPI_COMM_TYPE_CORE
OMPI_COMM_TYPE_HWTHREAD
OMPI_COMM_TYPE_CU
OMPI_COMM_TYPE_L3CACHE
OMPI_COMM_TYPE_L1CACHE
OMPI_COMM_TYPE_L2CACHE/;

