#!/bin/sh

# Copyright (c) 2015      Research Organization for Information Science
#                         and Technology (RIST). All rights reserved.

if [ $# -ne 4 ]; then
    echo "usage: $0 <OMPI_FORTRAN_CAPS> <OMPI_FORTRAN_PLAIN> <OMPI_FORTRAN_SINGLE_UNDERSCORE> <OMPI_FORTRAN_DOUBLE_UNDERSCORE>"
    exit 1
fi

OMPI_FORTRAN_CAPS=$1
OMPI_FORTRAN_PLAIN=$2
OMPI_FORTRAN_SINGLE_UNDERSCORE=$3
OMPI_FORTRAN_DOUBLE_UNDERSCORE=$4

if [ "X$OMPI_FORTRAN_CAPS" = X0 ] && [ "X$OMPI_FORTRAN_PLAIN" = X0 ] && [ "X$OMPI_FORTRAN_SINGLE_UNDERSCORE" = X0 ] && [ "X$OMPI_FORTRAN_DOUBLE_UNDERSCORE" = X0 ]; then
    # no fortran ...
    touch mpif-ompi-symbols.h
    touch mpif-oshmem-symbols.h
    exit 0
fi

mangle() {
    if [ "X$OMPI_FORTRAN_CAPS" = X1 ]; then
        echo $1 | tr [a-z] [A-Z]
    elif [ "X$OMPI_FORTRAN_PLAIN" = X1 ]; then
        echo $1 | tr [A-Z] [a-z]
    elif [ "X$OMPI_FORTRAN_SINGLE_UNDERSCORE" = X1 ]; then
        echo ${1}_ | tr [A-Z] [a-z]
    elif [ "X$OMPI_FORTRAN_DOUBLE_UNDERSCORE" = X1 ]; then
        echo ${1}__ | tr [A-Z] [a-z]
    fi
}

file=mpif-constants-decl.h
cat > $file << EOF
/* WARNING: This is a generated file!  Edits will be lost! */
/*
 * Copyright (c) 2015      Research Organization for Information Science
 *                         and Technology (RIST). All rights reserved.
 * \$COPYRIGHT\$
 *
 * This file was generated by gen-mpi-mangling.sh
 */

/* Note that the rationale for the types of each of these variables is
   discussed in ompi/include/mpif-common.h.  Do not change the types
   without also changing ompi/runtime/ompi_mpi_init.c and
   ompi/include/mpif-common.h. */

EOF

tmp=$(mktemp /tmp/ompi_symbols_XXXXXX)
cat > $tmp << EOF
    int mpi_fortran_bottom
    int mpi_fortran_in_place
    int mpi_fortran_unweighted
    int mpi_fortran_weights_empty
    char* mpi_fortran_argv_null
    char* mpi_fortran_argvs_null
    int* mpi_fortran_errcodes_ignore
    int* mpi_fortran_status_ignore
    int* mpi_fortran_statuses_ignore
EOF

make_constant() {
    echo "extern $1 $(mangle $2);" >> $3
    echo "#define $(echo $2 | sed -e s/^mpi_/OMPI_IS_/g | tr [a-z] [A-Z])(addr) \\" >> $3
    echo "        (addr == (void *) &$(mangle $2))" >> $3
    echo >> $3
}

cat $tmp | while read type symbol; do
    make_constant $type $symbol $file 
done

file=mpif-ompi-symbols.h
cat > $file << EOF
/* WARNING: This is a generated file!  Edits will be lost! */
/*
 * Copyright (c) 2015      Research Organization for Information Science
 *                         and Technology (RIST). All rights reserved.
 * \$COPYRIGHT\$
 *
 * This file was generated by gen-mpi-mangling.sh
 */

EOF

make_ompi_symbols() {
    echo "$1 $(mangle $2);" >> $3
}

cat $tmp | while read type symbol; do
    make_ompi_symbols $type $symbol $file
done

cat > $tmp << EOF
    int mpi_fortran_bottom
    int mpi_fortran_in_place
    char* mpi_fortran_argv_null
    char* mpi_fortran_argvs_null
    int* mpi_fortran_errcodes_ignore
    int* mpi_fortran_status_ignore
    int* mpi_fortran_statuses_ignore
EOF

file=mpif-oshmem-symbols.h
cat > $file << EOF
/* WARNING: This is a generated file!  Edits will be lost! */
/*
 * Copyright (c) 2015      Research Organization for Information Science
 *                         and Technology (RIST). All rights reserved.
 * \$COPYRIGHT\$
 *
 * This file was generated by gen-mpi-mangling.sh
 */

EOF

make_oshmem_symbols() {
    echo "$1 $(mangle $2);" >> $3
}

cat $tmp | while read type symbol; do
    make_oshmem_symbols $type $symbol $file
done

cat > $tmp << EOF
  type(MPI_STATUS) MPI_STATUS_IGNORE
  type(MPI_STATUS) MPI_STATUSES_IGNORE(1)
  integer MPI_BOTTOM
  integer MPI_IN_PLACE
  integer MPI_ARGV_NULL
  integer MPI_ARGVS_NULL
  integer MPI_ERRCODES_IGNORE
  integer MPI_UNWEIGHTED
  integer MPI_WEIGHTS_EMPTY
EOF

file=mpif-f08-types.h
cat > $file << EOF
! WARNING: This is a generated file!  Edits will be lost! */
!
! Copyright (c) 2015      Research Organization for Information Science
!                         and Technology (RIST). All rights reserved.
! \$COPYRIGHT\$
!
! This file was generated by gen-mpi-mangling.sh
!

EOF

make_f08() {
    echo "$1, bind(C, name=\"$(mangle $(echo $2 | sed -e s/^MPI_/MPI_FORTRAN_/g))\") :: $2" >> $3
}

cat $tmp | while read type symbol; do
    make_f08 $type $symbol $file
done

rm -f $tmp

