#!/usr/bin/env perl
#
# Copyright (c) 2013 Cisco Systems, Inc.  All rights reserved.
#
# $COPYRIGHT$
# 
# Additional copyrights may follow
# 
# $HEADER$
#

#
# Generate Fortran interface strings
#

package OMPI::Bodies;

use strict;

use FortranMPI::Emit::Bodies;

use OMPI::Utils;
use OMPI::Constants;
use OMPI::Handles;

my $types_module_name = "mpi_f08_types";
my $callbacks_module_name = "mpi_f08_interfaces_callbacks";

sub EmitMPI_F08 {
    my $args = shift;

    $args->{types_module_name} = $types_module_name;
    $args->{callbacks_module_name} = $callbacks_module_name;
    my $output = '! -*- f90 -*-
! THIS FILE IS AUTOMATICALLY GENERATED!
! Manual edits will be lost
!
! Copyright (c) 2015      Cisco Systems, Inc.  All rights reserved.
! Copyright (c) 2015      Research Organization for Information Science
!                         and Technology (RIST). All rights reserved.
! ' . $args->{gen_str} . '
!

';

    $args->{types_module_name} = $types_module_name;
    $args->{callbacks_module_name} = $callbacks_module_name;
    $output .= FortranMPI::Emit::Bodies::EmitMPI_F08($args);

    safe_write_file("ompi/mpi/fortran/use-mpi-f08/mpi-f08-module-bodies.F90",
                    $output);

    $output = '! -*- f90 -*-
! THIS FILE IS AUTOMATICALLY GENERATED!
! Manual edits will be lost
!
! Copyright (c) 2015      Cisco Systems, Inc.  All rights reserved.
! Copyright (c) 2015      Research Organization for Information Science
!                         and Technology (RIST). All rights reserved.
! ' . $args->{gen_str} . '
!

';

    $args->{types_module_name} = $types_module_name;
    $args->{callbacks_module_name} = $callbacks_module_name;
    $output .= FortranMPI::Emit::Bodies::EmitPMPI_F08($args);

    safe_write_file("ompi/mpi/fortran/use-mpi-f08/profile/pmpi-f08-module-bodies.F90",
                    $output);

}
